apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    name: ghcr-login-secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:jt99qp5t1jW/gykA/eUJvU2HQB3FxSSjZaaywJxLO2ehCXt2TXb3cVjh9hPzrLnOk9Y8nGgtJVlmzYXLk2ojcJFs4FTjSWWkQR8wQ/kaTufRG+WaX+fkhDWCfSe4e750dwsuNO60Jc4A6m1Dc9YiwSpCol4xnh57RXeLhVWsIWlmDuVx5w6DhycrmtWCh3YVxpO3mjHwZ5dt3dQ8yyu7+GWLtrJuEXf3PXTRdBQVt0bCEfPhgZHLC9BtK4WvzpfnWoNHbWcYB+IJcJ9xXPcooILm7VS2pV2Th3mOaFNP2vv3RpeOcwKi5/Vk5dcBkQo7VoYmAN928Gjq/7bV1Z8/CETge+WYSX7uNJSJxctQRTX00rTZm2pGT+8te44W0rYqXbmcn7QqdxiL0y2MdOB5uqx5NMc=,iv:+rLVpeUr05mx5ZGkyhiiAWmA3EvnOznfH/zvR6Te1Ws=,tag:IYfhKkzV4c1WJPNCAF6FQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWTFTdW44THFGSCs5S1VZ
            eTVVVlVkR05JcGJJKy9QN1dVWHM3MEF4bUJJCmUwRHJ3cGJNQXR6dHJNN2tGbWdZ
            QjltQTgzV0laOGNiNmU5UlZIZldPQVUKLS0tIFovRFByYjRWVW9KbnNlVG1WRjBs
            S1ZjcVZVMDBta1VWZmh6eE90UXg4ZzAK1GcbQLma0WsyYuRghOv4ewK6S1wgfzLn
            A2K28GUnpqTiNszZUC6OaC4x55rIYjZoizFugKjZDk0xhgaQKBpPnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T16:41:47Z"
    mac: ENC[AES256_GCM,data:2YhpjGgHxPYcriUevzGdWjgC0APG4Kj1zzy2kk7pvVrRzn3/7t9shQHV8r0r2QfZ3N4WG6M/astaVzlwDUPU7Ycqrqij+GA3QIopjMUjOa4iKzEfQSrPdyS5Rx6Qnz0dazTLsNWHLJtQ+OmpA6KK1VMjL62UehtgrsSEFLksHaU=,iv:Pc2ztLJRmeDDkO+baROIHu2S4Wpo4RVXss2dxV+A9oA=,tag:6d2V4XX0n0/1mmhGUFrutg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
