---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./amd-device-plugin.yaml
  - ./angelnu.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./influxdata.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./pihole.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./traefik.yaml
  - ./weave-gitops.yaml
