---
apiVersion: v1
kind: Service
metadata:
  name: octopi
  namespace: networking
  labels:
    app: octopi
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: octopi
  namespace: networking
  labels:
    app: octopi
subsets:
  - addresses:
      - ip: 192.168.10.80
    ports:
      - port: 80
