---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: networking
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: "${SECRET_DOMAIN/./-}-production-tls"
  routes:
    - match: "Host(`home-code.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: home-assistant-addon-codeserver
          namespace: home
          port: 12321
    - match: "Host(`influxdb.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: influxdb
          namespace: home
          port: 8086
    - match: "Host(`node-red.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: node-red
          namespace: home
          port: 1880
    - match: "Host(`zigbee2mqtt.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: zigbee2mqtt
          namespace: home
          port: 8080
