---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring
  namespace: networking
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: "${SECRET_DOMAIN/./-}-production-tls"
  routes:
    - match: "Host(`prometheus.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: kube-prometheus-stack-prometheus
          namespace: monitoring
          port: 9090
    - match: "Host(`grafana.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: grafana
          namespace: monitoring
          port: 80
    # - match: "Host(`loki.${SECRET_DOMAIN}`)"
    #   kind: Rule
    #   services:
    #     - kind: Service
    #       name: loki
    #       namespace: monitoring
    #       port: 3100
    - match: "Host(`hubble.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - kind: Service
          name: hubble-ui
          namespace: kube-system
          port: 80
