---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi
  namespace: network
spec:
  secretName: unifi-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: unifi.${SECRET_DOMAIN}
  dnsNames:
    - "unifi.${SECRET_DOMAIN}"
