---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cabinet-envoy
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_WEB_CABINET}"
  labels:
    external-dns: enabled
spec:
  gatewayClassName: envoy-gateway
  addresses:
    - type: IPAddress
      value: 192.168.42.65
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "192.168.42.65"
      external-dns.alpha.kubernetes.io/hostname: "external.${SECRET_DOMAIN_WEB_CABINET}"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cabinet-piet-tls
            namespace: kube-system
